---
language: shell
services:
  - docker
  - postgresql
if: 'type = push'

# Environment variables defined as part of the Travis CI repository configuration are:
# - DOCKER_ORG: the docker hub organization (or user) to which the image will be pushed
# - DOCKER_USER: the docker hub user used to log in to the docker hub
# - DOCKER_PASS: the password of this user
# - GEOSPAAS_DB_PASSWORD: the password for connecting to the test database

env:
  global:
    - BASE_IMAGE_NAME="${DOCKER_ORG}/geospaas:v0.4"
    - METANORM_VERSION='0.0.1'

jobs:
  include:
    - stage: 'Unit tests'
      env:
        - GEOSPAAS_DB_HOST='db'
        - GEOSPAAS_DB_USER='test'
        - LOG_DIR='logs'
      install:
        - mkdir "$LOG_DIR"
        - docker network create testing
        - >
          docker run -d --rm
          --network testing
          --name "$GEOSPAAS_DB_HOST"
          -e "POSTGRES_USER=$GEOSPAAS_DB_USER" -e "POSTGRES_PASSWORD=$GEOSPAAS_DB_PASSWORD"
          postgis/postgis:12-2.5
      script:
        - >
          docker run --rm
          --network testing
          -v "$(pwd):/src" -v "$(pwd)/${LOG_DIR}:/var/log/geospaas"
          -e "COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN"
          -e "TRAVIS=true" -e "TRAVIS_JOB_ID=$TRAVIS_JOB_ID"
          -e "TRAVIS_BRANCH=$TRAVIS_BRANCH" -e "TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
          -e "GEOSPAAS_DB_HOST=$GEOSPAAS_DB_HOST"
          -e "GEOSPAAS_DB_USER=$GEOSPAAS_DB_USER" -e "GEOSPAAS_DB_PASSWORD=$GEOSPAAS_DB_PASSWORD"
          "${BASE_IMAGE_NAME}"
          bash -c "source /opt/conda/bin/activate
          && pip install 'https://github.com/nansencenter/metanorm/releases/download/${METANORM_VERSION}/metanorm-${METANORM_VERSION}-py3-none-any.whl'
          && coverage run --source=./geospaas_harvesting ./runtests.py
          && coveralls"
...