---
name: "Unit tests and docker image build"
on:
  - push
  - pull_request
env:
  BASE_IMAGE_NAME: "${{ secrets.DOCKER_ORG }}/geospaas:2.4.0-slim"
  METANORM_VERSION: '3.1.2'
jobs:
  tests:
    runs-on: 'ubuntu-20.04'
    env:
      GEOSPAAS_DB_HOST: 'db'
      GEOSPAAS_DB_USER: 'test'
      IMAGE_NAME: 'harvesting_tests'
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: 'Create test docker network'
        run: docker network create testing

      - name: 'Build testing image'
        run: >
             docker build .
             -t "${IMAGE_NAME}"
             --build-arg "BASE_IMAGE=${BASE_IMAGE_NAME}"
             --build-arg "METANORM_VERSION=$METANORM_VERSION"
             --target base

      - name: 'Start testing database'
        run: /bin/bash ./scripts/start_test_database.sh

      - name: 'Run tests'
        run: >
             docker run --rm
             --network testing
             -v "$(pwd):/src"
             -e "COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN"
             -e "TRAVIS=true"
             -e "TRAVIS_JOB_ID=$TRAVIS_JOB_ID"
             -e "TRAVIS_BRANCH=$TRAVIS_BRANCH"
             -e "TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
             -e "GEOSPAAS_DB_HOST=$GEOSPAAS_DB_HOST"
             -e "GEOSPAAS_DB_USER=$GEOSPAAS_DB_USER"
             -e "GEOSPAAS_DB_PASSWORD=$GEOSPAAS_DB_PASSWORD"
             "${IMAGE_NAME}"
             bash -c "coverage run --source=./geospaas_harvesting ./runtests.py && coveralls"

      - name: 'Stop testing database'
        run: docker stop "$GEOSPAAS_DB_HOST"


  build_docker_image:
    runs-on: 'ubuntu-20.04'
    needs: 'tests'
    if: ${{ github.event_name == 'tag' || github.event_name == 'pull_request' }}
    env:
      IMAGE_NAME: "${{ secrets.DOCKER_ORG }}/geospaas_harvesting"
    steps:
      - name: "Extract tag name"
        id: get_version
        run: echo "::set-output name=VERSION::${GITHUB_REF#refs/tags/}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            BASE_IMAGE='${{ env.BASE_IMAGE_NAME }}'
            METANORM_VERSION='${{ env.METANORM_VERSION }}'
          push: ${{ github.event_name == 'tag' }}
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
...